### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ip6tables-save'

### ISSUE THREAD

**Issue by saharakks** [binhex/arch-privoxyvpn#38]
`proton-proxy-0  | Traceback (most recent call last):
proton-proxy-0  |   File "/usr/bin/protonvpn", line 33, in <module>
proton-proxy-0  | Connecting to CH#399 via UDP...
proton-proxy-0  |     sys.exit(load_entry_point('protonvpn-cli==2.2.12', 'console_scripts', 'protonvpn')())
proton-proxy-0  |   File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 72, in main
proton-proxy-0  |     cli()
proton-proxy-0  |   File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 119, in cli
proton-proxy-0  |     connection.random_c(protocol)
proton-proxy-0  |   File "/usr/lib/python3.10/site-packages/protonvpn_cli/connection.py", line 155, in random_c
proton-proxy-0  |     openvpn_connect(servername, protocol)
proton-proxy-0  |   File "/usr/lib/python3.10/site-packages/protonvpn_cli/connection.py", line 517, in openvpn_connect
proton-proxy-0  |     manage_ipv6("disable")
proton-proxy-0  |   File "/usr/lib/python3.10/site-packages/protonvpn_cli/connection.py", line 677, in manage_ipv6
proton-proxy-0  |     ip6tables_rules = subprocess.run(["ip6tables-save"],
proton-proxy-0  |   File "/usr/lib/python3.10/subprocess.py", line 503, in run
proton-proxy-0  |     with Popen(*popenargs, **kwargs) as process:
proton-proxy-0  |   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
proton-proxy-0  |     self._execute_child(args, executable, preexec_fn, close_fds,
proton-proxy-0  |   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
proton-proxy-0  |     raise child_exception_type(errno_num, err_msg, err_filename)
proton-proxy-0  | FileNotFoundError: [Errno 2] No such file or directory: 'ip6tables-save'`

**Comment by saharakks** [comment]
using image walt3rl/proton-privoxy:latest (2c5984ae5c6d)

**Comment by saharakks** [comment]
Sorry posted in totally irrelevent repo.
